version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8090:8090"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8091:8091"
  
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
