version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - db 

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8091:8091"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - ./database/.env

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
