import dash
import dash_bootstrap_components as dbc
from dash import html

from src import ids
from src.components.chile_map import ChileMap
from src.components import buscador_recorrido
from src.components.tabla_recorridos import TablaRecorridos

def render(app: dash.Dash) -> dbc.Container:
    """
    Generates a layout object containing a header and a choropleth map generated by
    the choropleth.render function.

    Args:
    - app (Dash object): The Dash app.

    Returns:
    - layout (dbc.Container object): The layout object.
    """
    title = "Parques Vehiculares"
    chile_map = ChileMap(app)
    tabla_recorridos = TablaRecorridos(app)
    
    layout = dbc.Container([
        dbc.Row([
            html.H1(title),
            buscador_recorrido.render(app),
            tabla_recorridos.render(),
            chile_map.render()
        ])
    ])

    return layout
