import dash
import dash_bootstrap_components as dbc
from dash import html


from src.components.chile_map import ChileMap
from src.components import buscador_recorrido, tabla_recorridos, detalle_ruta


def render(app: dash.Dash) -> dbc.Container:
    """
    Generates a layout object containing a header and a choropleth map generated by
    the choropleth.render function.

    Args:
    - app (Dash object): The Dash app.

    Returns:
    - layout (dbc.Container object): The layout object.
    """
    title = "Parques Vehiculares"
    chile_map = ChileMap(app)

    layout = dbc.Container(
        [
            dbc.Row(
                [
                    html.H1(title),
                    buscador_recorrido.render(app),
                    tabla_recorridos.render(app),
                    dbc.Col(
                        detalle_ruta.render(app),
                    ),
                    chile_map.render(),
                ]
            )
        ]
    )

    return layout
