import dash
import dash_bootstrap_components as dbc
from dash import html

from src import ids
from src.components.chile_map import ChileMap
from src.components import (
    buscador_recorrido,
    tabla_recorridos,
    detalle_ruta,
    vehiculos_info,
)


def render(app: dash.Dash) -> dbc.Container:
    """
    Generates a layout object containing a header and a choropleth map generated by
    the choropleth.render function.

    Args:
    - app (Dash object): The Dash app.

    Returns:
    - layout (dbc.Container object): The layout object.
    """
    title = "Buscador de Parques Vehiculares"
    chile_map = ChileMap(app)
    separator = html.Div(
        className="vertical-separator",
        style={
            "border-right": "1px solid #ccc",
            "margin": "0 10px",
            "height": "100%",
        },
    )

    layout = dbc.Container(
        [
            dbc.Row(
                [
                    html.H1(title, id=ids.TITLE),
                    buscador_recorrido.render(app),
                    tabla_recorridos.render(app),
                    dbc.Col(
                        [
                            detalle_ruta.render(app),
                            separator,
                            vehiculos_info.render(app),
                        ],
                        # width=4,
                        style={"display": "flex"},
                    ),
                    chile_map.render(),
                ]
            )
        ]
    )

    return layout
